In [14]:
import pandas as pd, cufflinks as cf

In [15]:
from IPython.display import display,HTML
cf.set_config_file(sharing='plubic',theme='ggplot',offline=True)

In [86]:
game = pd.read_excel('/Users/Hydral/Documents/Enviromen/video_games\Ventas+Videojuegos.xlsx')
game.head()

,Nombre,Plataforma,Año,Genero,Editorial,Ventas NA,Ventas EU,Ventas JP,Ventas Otros,Ventas Global
0,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [83]:
#Limpieza de valores

#comprobando valores nulos
#game_null = game.isna()

#elimnando valores nulos
#game_drop = game.dropna()


Renombrando columnas

In [87]:
game = game.rename(columns={'Ventas NA':'Norte America','Ventas EU':'Europa','Ventas JP':'Japon','Ventas Otros':'Otros','Ventas Global':'Total Ventas'})
game.head()

,Nombre,Plataforma,Año,Genero,Editorial,Norte America,Europa,Japon,Otros,Total Ventas
0,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [123]:
#Pormedio ventas por nombre
game_avg_name = game.iloc[:,[5,6,7,8]].mean(axis=1)
game_avg.head()

#promedio ventas por continente
game_avg_cont = game.iloc[:,[5,6,7,8]].mean(axis=0)

#promedios ventas por Editorial
editorial_avg = game.iloc[0:,[4,5,6,7,8]]
editorial_avg = editorial_avg.groupby(['Editorial'])[['Norte America','Europa','Japon','Otros']].agg('sum')


editorial_avg.descensing=True
editorial_avg

                              Norte America  Europa  Japon  Otros
Editorial
10TACLE Studios                        0.07    0.04   0.00   0.00
1C Company                             0.01    0.07   0.00   0.02
20th Century Fox Video Games           1.82    0.10   0.00   0.01
2D Boy                                 0.00    0.03   0.00   0.01
3DO                                    6.48    3.04   0.00   0.63
...                                     ...     ...    ...    ...
id Software                            0.02    0.00   0.00   0.00
imageepoch Inc.                        0.00    0.00   0.04   0.00
inXile Entertainment                   0.02    0.06   0.00   0.01
mixi, Inc                              0.00    0.00   0.86   0.00
responDESIGN                           0.09    0.04   0.00   0.01

[576 rows x 4 columns]